### ISSUE TITLE
I am back - I can do full testing now :D

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [rheimus/ServerSync#9]
Hey so I am back finally - took a bit but I am here.

**Comment by P3rf3ctXZer0** [comment]
Really impressed with newest builds

**Comment by Iomega0318** [comment]
I'll gladly help test as well, was just reading the 2.0 mod thread, very nice indeed. Was looking for a simple way of doing this for a family server :)

**Comment by rheimus** [comment]
Currently both 2.0 and 3.0 are suffering from seemingly random file sync failure.

I was going to push forward with some more individual file focused features that may help highlight where the issue is, as it stands I have had no luck reproducing the issue in an environment which I can get any useful data from.

**Comment by P3rf3ctXZer0** [comment]
When you need me I am here and yeah I can vouch for the same issues you just mentioned.

**Comment by P3rf3ctXZer0** [comment]
Sorry finger slipped - I got to sleep - gnite.

**Comment by Iomega0318** [comment]
If you need a server to test on let me know, I use a private one for friends and family that I play around on. I'm going to be downloading this today so I can play around with it.
